# Auto-generated extras metadata from LazyVim
# Generated by scripts/generate-extras-metadata.sh
# DO NOT EDIT MANUALLY

{
  ai = {
    "codeium" = {
      name = "codeium";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.codeium";
    };
    "copilot_chat" = {
      name = "copilot-chat";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.copilot-chat";
    };
    "copilot" = {
      name = "copilot";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.copilot";
    };
    "copilot_native" = {
      name = "copilot-native";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.copilot-native";
    };
    "sidekick" = {
      name = "sidekick";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.sidekick";
    };
    "supermaven" = {
      name = "supermaven";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.supermaven";
    };
    "tabnine" = {
      name = "tabnine";
      category = "ai";
      import = "lazyvim.plugins.extras.ai.tabnine";
    };
  };
  coding = {
    "blink" = {
      name = "blink";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.blink";
    };
    "luasnip" = {
      name = "luasnip";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.luasnip";
    };
    "mini_comment" = {
      name = "mini-comment";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.mini-comment";
    };
    "mini_snippets" = {
      name = "mini-snippets";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.mini-snippets";
    };
    "mini_surround" = {
      name = "mini-surround";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.mini-surround";
    };
    "neogen" = {
      name = "neogen";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.neogen";
    };
    "nvim_cmp" = {
      name = "nvim-cmp";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.nvim-cmp";
    };
    "yanky" = {
      name = "yanky";
      category = "coding";
      import = "lazyvim.plugins.extras.coding.yanky";
    };
  };
  dap = {
    "core" = {
      name = "core";
      category = "dap";
      import = "lazyvim.plugins.extras.dap.core";
    };
    "nlua" = {
      name = "nlua";
      category = "dap";
      import = "lazyvim.plugins.extras.dap.nlua";
    };
  };
  editor = {
    "aerial" = {
      name = "aerial";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.aerial";
    };
    "dial" = {
      name = "dial";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.dial";
    };
    "fzf" = {
      name = "fzf";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.fzf";
    };
    "harpoon2" = {
      name = "harpoon2";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.harpoon2";
    };
    "illuminate" = {
      name = "illuminate";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.illuminate";
    };
    "inc_rename" = {
      name = "inc-rename";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.inc-rename";
    };
    "leap" = {
      name = "leap";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.leap";
    };
    "mini_diff" = {
      name = "mini-diff";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.mini-diff";
    };
    "mini_files" = {
      name = "mini-files";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.mini-files";
    };
    "mini_move" = {
      name = "mini-move";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.mini-move";
    };
    "navic" = {
      name = "navic";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.navic";
    };
    "neo_tree" = {
      name = "neo-tree";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.neo-tree";
    };
    "outline" = {
      name = "outline";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.outline";
    };
    "overseer" = {
      name = "overseer";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.overseer";
    };
    "refactoring" = {
      name = "refactoring";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.refactoring";
    };
    "snacks_explorer" = {
      name = "snacks_explorer";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.snacks_explorer";
    };
    "snacks_picker" = {
      name = "snacks_picker";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.snacks_picker";
    };
    "telescope" = {
      name = "telescope";
      category = "editor";
      import = "lazyvim.plugins.extras.editor.telescope";
    };
  };
  formatting = {
    "biome" = {
      name = "biome";
      category = "formatting";
      import = "lazyvim.plugins.extras.formatting.biome";
    };
    "black" = {
      name = "black";
      category = "formatting";
      import = "lazyvim.plugins.extras.formatting.black";
    };
    "prettier" = {
      name = "prettier";
      category = "formatting";
      import = "lazyvim.plugins.extras.formatting.prettier";
    };
  };
  lang = {
    "angular" = {
      name = "angular";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.angular";
    };
    "ansible" = {
      name = "ansible";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.ansible";
    };
    "astro" = {
      name = "astro";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.astro";
    };
    "clangd" = {
      name = "clangd";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.clangd";
    };
    "clojure" = {
      name = "clojure";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.clojure";
    };
    "cmake" = {
      name = "cmake";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.cmake";
    };
    "docker" = {
      name = "docker";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.docker";
    };
    "elixir" = {
      name = "elixir";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.elixir";
    };
    "elm" = {
      name = "elm";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.elm";
    };
    "erlang" = {
      name = "erlang";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.erlang";
    };
    "git" = {
      name = "git";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.git";
    };
    "gleam" = {
      name = "gleam";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.gleam";
    };
    "go" = {
      name = "go";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.go";
    };
    "haskell" = {
      name = "haskell";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.haskell";
    };
    "helm" = {
      name = "helm";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.helm";
    };
    "java" = {
      name = "java";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.java";
    };
    "json" = {
      name = "json";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.json";
    };
    "kotlin" = {
      name = "kotlin";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.kotlin";
    };
    "lean" = {
      name = "lean";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.lean";
    };
    "markdown" = {
      name = "markdown";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.markdown";
    };
    "nix" = {
      name = "nix";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.nix";
    };
    "nushell" = {
      name = "nushell";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.nushell";
    };
    "ocaml" = {
      name = "ocaml";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.ocaml";
    };
    "omnisharp" = {
      name = "omnisharp";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.omnisharp";
    };
    "php" = {
      name = "php";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.php";
    };
    "prisma" = {
      name = "prisma";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.prisma";
    };
    "python" = {
      name = "python";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.python";
    };
    "rego" = {
      name = "rego";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.rego";
    };
    "r" = {
      name = "r";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.r";
    };
    "ruby" = {
      name = "ruby";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.ruby";
    };
    "rust" = {
      name = "rust";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.rust";
    };
    "scala" = {
      name = "scala";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.scala";
    };
    "sql" = {
      name = "sql";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.sql";
    };
    "svelte" = {
      name = "svelte";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.svelte";
    };
    "tailwind" = {
      name = "tailwind";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.tailwind";
    };
    "terraform" = {
      name = "terraform";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.terraform";
    };
    "tex" = {
      name = "tex";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.tex";
    };
    "thrift" = {
      name = "thrift";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.thrift";
    };
    "toml" = {
      name = "toml";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.toml";
    };
    "typescript" = {
      name = "typescript";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.typescript";
    };
    "vue" = {
      name = "vue";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.vue";
    };
    "yaml" = {
      name = "yaml";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.yaml";
    };
    "zig" = {
      name = "zig";
      category = "lang";
      import = "lazyvim.plugins.extras.lang.zig";
    };
  };
  linting = {
    "eslint" = {
      name = "eslint";
      category = "linting";
      import = "lazyvim.plugins.extras.linting.eslint";
    };
  };
  lsp = {
    "neoconf" = {
      name = "neoconf";
      category = "lsp";
      import = "lazyvim.plugins.extras.lsp.neoconf";
    };
    "none_ls" = {
      name = "none-ls";
      category = "lsp";
      import = "lazyvim.plugins.extras.lsp.none-ls";
    };
  };
  test = {
    "core" = {
      name = "core";
      category = "test";
      import = "lazyvim.plugins.extras.test.core";
    };
  };
  ui = {
    "alpha" = {
      name = "alpha";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.alpha";
    };
    "dashboard_nvim" = {
      name = "dashboard-nvim";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.dashboard-nvim";
    };
    "edgy" = {
      name = "edgy";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.edgy";
    };
    "indent_blankline" = {
      name = "indent-blankline";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.indent-blankline";
    };
    "mini_animate" = {
      name = "mini-animate";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.mini-animate";
    };
    "mini_indentscope" = {
      name = "mini-indentscope";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.mini-indentscope";
    };
    "mini_starter" = {
      name = "mini-starter";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.mini-starter";
    };
    "smear_cursor" = {
      name = "smear-cursor";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.smear-cursor";
    };
    "treesitter_context" = {
      name = "treesitter-context";
      category = "ui";
      import = "lazyvim.plugins.extras.ui.treesitter-context";
    };
  };
  util = {
    "chezmoi" = {
      name = "chezmoi";
      category = "util";
      import = "lazyvim.plugins.extras.util.chezmoi";
    };
    "dot" = {
      name = "dot";
      category = "util";
      import = "lazyvim.plugins.extras.util.dot";
    };
    "gitui" = {
      name = "gitui";
      category = "util";
      import = "lazyvim.plugins.extras.util.gitui";
    };
    "mini_hipatterns" = {
      name = "mini-hipatterns";
      category = "util";
      import = "lazyvim.plugins.extras.util.mini-hipatterns";
    };
    "octo" = {
      name = "octo";
      category = "util";
      import = "lazyvim.plugins.extras.util.octo";
    };
    "project" = {
      name = "project";
      category = "util";
      import = "lazyvim.plugins.extras.util.project";
    };
    "rest" = {
      name = "rest";
      category = "util";
      import = "lazyvim.plugins.extras.util.rest";
    };
    "startuptime" = {
      name = "startuptime";
      category = "util";
      import = "lazyvim.plugins.extras.util.startuptime";
    };
  };
}
