# GitHub Actions CI Template for Plugin Testing with LazyVim
# Place in: .github/workflows/test.yml

name: Test Plugin with LazyVim

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Quick validation (runs first)
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Nix formatting
        run: |
          nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."

  # Main test suite
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against multiple Neovim versions
        neovim: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      # Optional: Setup Cachix for faster builds
      - uses: cachix/cachix-action@v12
        with:
          name: your-cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build test config
        run: |
          nix-build tests/plugin-test.nix -A testConfig -o test-nvim
          echo "Config: $(readlink test-nvim)"

      - name: Run load test
        run: nix-build tests/plugin-test.nix -A testLoad

      - name: Run setup test
        run: nix-build tests/plugin-test.nix -A testSetup

      - name: Run test suite
        run: nix-build tests/plugin-test.nix -A testAll

      # Optional: Upload test artifacts
      - name: Upload test config
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-config-${{ matrix.neovim }}
          path: test-nvim/

  # Integration test with real files
  integration:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - name: Build test config
        run: nix-build tests/plugin-test.nix -A testConfig -o test-nvim

      - name: Test with sample files
        run: |
          # Create test file
          cat > test.lua << 'EOF'
          -- Test file
          local M = {}
          function M.test() print("hello") end
          return M
          EOF

          # Run Neovim on test file
          nix-shell -p neovim --run \
            "nvim -u test-nvim/init.lua test.lua \
             --headless +'lua print(\"Processing test.lua\")' +quit"

  # Performance benchmark (optional)
  benchmark:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - name: Benchmark startup time
        run: |
          nix-build tests/plugin-test.nix -A testConfig -o test-nvim

          nix-shell -p neovim --run \
            "time nvim -u test-nvim/init.lua \
             --headless --startuptime startup.log +quit"

          cat startup.log

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: startup.log

# Minimal template (if you just need basic CI):
#
# name: Test
# on: [push, pull_request]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: cachix/install-nix-action@v24
#       - run: nix-build tests/plugin-test.nix -A testCI
