name: Update LazyVim Plugins

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'scripts/update-plugins.sh'
      - 'scripts/extract-plugins.lua'
      - 'scripts/suggest-mappings.lua'
      - '.github/workflows/update-plugins.yml'

jobs:
  update-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26
        
      - name: Setup Nix cache
        uses: cachix/cachix-action@v12
        with:
          name: nix-community
          
      - name: Check for LazyVim updates
        id: check-updates
        run: |
          # Get current version from plugins.json
          if [ -f plugins.json ]; then
            CURRENT_VERSION=$(jq -r '.version' plugins.json)
            CURRENT_COMMIT=$(jq -r '.commit' plugins.json)
          else
            CURRENT_VERSION="none"
            CURRENT_COMMIT="none"
          fi
          
          # Get latest LazyVim version
          LATEST_VERSION=$(git ls-remote --tags https://github.com/LazyVim/LazyVim.git | grep -v '\^{}' | tail -1 | sed 's/.*\///')
          LATEST_COMMIT=$(git ls-remote https://github.com/LazyVim/LazyVim.git HEAD | cut -f1)
          
          echo "Current version: $CURRENT_VERSION ($CURRENT_COMMIT)"
          echo "Latest version: $LATEST_VERSION ($LATEST_COMMIT)"
          
          if [ "$CURRENT_COMMIT" != "$LATEST_COMMIT" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Update plugins
        if: steps.check-updates.outputs.update_needed == 'true'
        id: update-plugins
        run: |
          # Run with verification enabled
          nix develop --command ./scripts/update-plugins.sh --verify
          
          # Check if there are unmapped plugins
          UNMAPPED_COUNT=$(jq '.extraction_report.unmapped_plugins // 0' plugins.json)
          echo "unmapped_count=$UNMAPPED_COUNT" >> $GITHUB_OUTPUT
          
          # If unmapped plugins exist, extract mapping suggestions
          if [ "$UNMAPPED_COUNT" -gt 0 ] && [ -f mapping-analysis-report.md ]; then
            # Extract verified mappings from the report
            if grep -q "## ✅ Verified Mappings" mapping-analysis-report.md; then
              echo "has_verified_mappings=true" >> $GITHUB_OUTPUT
              
              # Extract the nix code block with mappings
              sed -n '/```nix/,/```/p' mapping-analysis-report.md | sed '1d;$d' > new-mappings.nix
              
              # Apply the mappings to plugin-mappings.nix
              if [ -s new-mappings.nix ]; then
                # Insert before the closing brace
                sed -i '$ s/}//' plugin-mappings.nix
                cat new-mappings.nix >> plugin-mappings.nix
                echo "}" >> plugin-mappings.nix
                
                # Re-run extraction with new mappings
                nix develop --command ./scripts/update-plugins.sh
              fi
            else
              echo "has_verified_mappings=false" >> $GITHUB_OUTPUT
            fi
          fi
          
      - name: Create Pull Request
        if: steps.check-updates.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update LazyVim plugins to ${{ steps.check-updates.outputs.latest_version }}"
          title: "Update LazyVim plugins to ${{ steps.check-updates.outputs.latest_version }}"
          body: |
            This PR updates the LazyVim plugin specifications to the latest version.
            
            ## Changes
            - Updated `plugins.json` with latest LazyVim plugin list
            - Version: ${{ steps.check-updates.outputs.latest_version }}
            ${{ steps.update-plugins.outputs.has_verified_mappings == 'true' && '- Added new verified plugin mappings to `plugin-mappings.nix`' || '' }}
            ${{ steps.update-plugins.outputs.unmapped_count > 0 && steps.update-plugins.outputs.has_verified_mappings != 'true' && '- ⚠️ Found unmapped plugins that need manual review (see mapping-analysis-report.md)' || '' }}
            
            ## Plugin Statistics
            - Total plugins: $(jq '.extraction_report.total_plugins // 0' plugins.json || echo "N/A")
            - Mapped plugins: $(jq '.extraction_report.mapped_plugins // 0' plugins.json || echo "N/A")
            - Unmapped plugins: ${{ steps.update-plugins.outputs.unmapped_count || 0 }}
            - Multi-module plugins: $(jq '.extraction_report.multi_module_plugins // 0' plugins.json || echo "N/A")
            
            ## Checklist
            - [ ] Review plugin changes
            - [ ] Test with example configuration
            ${{ steps.update-plugins.outputs.unmapped_count > 0 && '- [ ] Review mapping-analysis-report.md for unmapped plugins' || '- [x] All plugins are mapped' }}
            
            ---
            *This pull request was automatically generated by the update workflow.*
          branch: update-lazyvim-plugins
          delete-branch: true
          add-paths: |
            plugins.json
            plugin-mappings.nix
            mapping-analysis-report.md
          
  test-flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs:
          - nixos-unstable
          - nixos-23.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v26
        
      - name: Test flake
        run: |
          # Check flake
          nix flake check
          
          # Build the update script
          nix build .#default
          
          # Test the home-manager module evaluation
          nix eval .#homeManagerModules.default --apply 'module: if builtins.isAttrs module then "Module loads successfully" else "Failed to load module"'